// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testSQl.Data;

#nullable disable

namespace testSQl.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231213142656_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("testSQl.Model.DoubleGlazedWindows", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Chamberness")
                        .HasColumnType("int");

                    b.Property<int>("GlassThickness")
                        .HasColumnType("int");

                    b.Property<int>("ThicknessSP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DoubleGlazedWindows");
                });
#pragma warning restore 612, 618
        }
    }
}
